# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Posts"
  url = "/post"
  weight = 2

[[main]]
  name = "Research"
  url = "/research"
  weight = 3

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 4

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 5

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "/cv"
    weight = 6


