language: node_js
node_js: stable

branches:
  only:
  - src

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'

install:
  - yarn global add hexo-cli
  - yarn

script:
#  - hexo clean
  - hexo generate

after_success:
  - git config --global user.name $GIT_NAME
  - git config --global user.email $GIT_EMAIL
  - sed -i "s/GH_TOKEN/$GH_TOKEN/g" ./_config.yml
  - hexo deploy -m "Travis CI Build ${TRAVIS_BUILD_NUMBER}"

notifications:
  email:
    recipients:
      - $GIT_EMAIL
    on_success: change # default: change
    on_failure: always # default: always